CREATE TABLE visite (
  id INT(11) NOT NULL AUTO_INCREMENT,
  IMMOBILIER_ID INT(11) NOT NULL,
  AGENT_ID INT(11) NOT NULL,
  CLIENT_ID INT(11) NOT NULL,
  dateVisite DATETIME NOT NULL,

  PRIMARY KEY('id'),
  FOREIGN KEY 'IMMOBILIER_ID' REFERENCES bien()
);